Mi-1159 add logic to filter posts with embedded links
mattermost-community/mattermost-plugin-link-filter pull request #1
Opened 2021-02-08 12:09 UTC by hrishavkmr

2021-02-09 11:47 UTC, chetanyakan requested changes

2021-02-09 11:47 UTC, chetanyakan commented on .golangci.yml
> +    local-prefixes: github.com/mattermost/mattermost-plugin-autolink
rename this

2021-02-09 11:47 UTC, chetanyakan commented on go.mod
> +	github.com/mattermost/mattermost-server/v5 v5.23.1
We should either use the minimum server version supported by the APIs or verify the MM version in use.

2021-02-09 11:47 UTC, chetanyakan commented on plugin.json
> +        "type": "text",
Probably makes sense to use `longtext` here instead.

```suggestion
        "type": "longtext",
```

2021-02-09 11:47 UTC, chetanyakan commented on plugin.json
> +        "type": "longtext",
Maybe `text` would be sufficient.
```suggestion
        "type": "text",
```

2021-02-09 11:47 UTC, chetanyakan commented on plugin.json
> +        "default": "http,https"
From the e-mail
> The approved ones we definitely want to allow are http:, https:, mailto:. You also have mattermost: which I assume is required for Mattermost to function. All others will be excluded.

2021-02-09 11:47 UTC, chetanyakan commented on server/plugin.go
> +	regexString = `(?P<protocol>\w+)://(?P<host>[^\n)]+)?`
nit - Create constants for these regexes with a comment of what they would match.

2021-02-09 11:47 UTC, chetanyakan commented on server/plugin.go
> +		protocol := string(postText[loc[4]:loc[5]])
nit - you can also assign `loc[4]`, `loc[5]` to meaningfully named constants for better understandability.

2021-02-09 11:47 UTC, chetanyakan commented on server/plugin.go
> +			protocol = string(postText[loc[2]:loc[3]])
same here

2021-02-09 11:47 UTC, chetanyakan commented on server/util/util.go
> +func TrimString(textList []string) []string {
Is this used anywhere?

2021-02-09 11:58 UTC, hrishavkmr commented on server/util/util.go
> +func TrimString(textList []string) []string {
yes, https://github.com/Brightscout/mattermost-plugin-link-filter/pull/1/files#diff-065f09c83ba4f3083feef6a8ea1f19ab382d993d8cb51045b63a329c07c51ea0R104
this function is used to trim space and remove the empty strings from the list.

2021-02-09 11:59 UTC, hrishavkmr commented on plugin.json
> +        "default": "http,https"
done

2021-02-09 12:13 UTC, hrishavkmr commented on server/plugin.go
> +			protocol = string(postText[loc[2]:loc[3]])
done

2021-02-09 12:13 UTC, hrishavkmr commented on server/plugin.go
> +		protocol := string(postText[loc[4]:loc[5]])
done

2021-02-09 12:14 UTC, hrishavkmr commented on server/plugin.go
> +	regexString = `(?P<protocol>\w+)://(?P<host>[^\n)]+)?`
done

2021-02-09 12:15 UTC, hrishavkmr commented on .golangci.yml
> +    local-prefixes: github.com/mattermost/mattermost-plugin-autolink
done

2021-02-10 07:22 UTC, chetanyakan commented on .golangci.yml
> +    local-prefixes: github.com/mattermost/mattermost-plugin-link-filter
Should be same as the value in `go.mod`
```suggestion
    local-prefixes: github.com/Brightscout/mattermost-plugin-link-filter
```

2021-02-10 07:26 UTC, chetanyakan approved these changes

2021-02-10 07:46 UTC, merged